### ISSUE TITLE
input and output options are missing in 2.1.9

### ISSUE THREAD

**Issue by Espermachine** [dtschump/gmic-community#118]
Im on win7 64 bit. Input and output options are missing in the G'MIC interface.
Used the installer.

![missing](https://user-images.githubusercontent.com/14295623/35228362-d3cb0c3a-ff90-11e7-9ac3-10594abd1c22.jpg)

**Comment by dtschump** [comment]
There is a slider at the bottom of the filter parameters that you can shift to make the in/out parameters appear. It should have appeared normally the first time you launched the plug-in.

**Comment by Espermachine** [comment]
Sorry, im lost here. What slider ?

This is the first time, this feature is missing for me.

**Comment by dtschump** [comment]
This one.

https://imgur.com/a/4IOEs

**Comment by Espermachine** [comment]
Okay, i found it. Thank you !

But there is nothing that would have told me that there is something i can pull out. I dont have the three dots you have. There is just a line, that is part of the interface design.

**Comment by dtschump** [comment]
Actually, the I/O parameters should have been visible at the first time. We don't understand what has been going on, there is probably something we need to fix in the code, because you are the second person to report that issue.
So far, we didn't manage to reproduce it, on Linux or on Windows, so that's a bit annoying for us, because we have no easy way to understand the cause of that behavior.
