### ISSUE TITLE
New String handling

### ISSUE THREAD

**Issue by souphead** [dtschump/gmic-community#44]
Still getting errors with the new string handling:-

#@gimp aFun : afun, afun_preview(1)
#@gimp : X Tine Value = text{"test"}

afun_preview :
  -afun "${1--1}"

afun :
  -repeat $! -l[$>]
  -f. "
init(

str=uppercase(['$1']);

length=size(str);

length=length-1;
print(length);
sub_str=str[3,6];   # line 1
length=size(sub_str);   #line 2
print(length);

);

0"
-endl -done

If I run this, sub_str contains the all of str except the first three characters. For example, if I have a 7 character length string, it prints "6" and "4".

If I change line #1 to **sub_str=str[3,length];** , I get the following error: **"Operator '[]': Second argument (of type 'scalar') is not a positive integer constant, in expression '...str=str[3,length]...'."** . From the first test, the value of length should be "6" (based on a 7 character starting string) but I get this error, as if the variable isn't being substituted.

If I change Lines 1 & 2 to **str=str[3,6]; length=size(str);** I get the following error: **"Operator '=': Right-hand operator has invalid type 'vector4' (should be 'scalar' or 'vector7'), in expression '...h); str=str[3,6]; length=size(str); print(length...'."** . This would imply that I can't overwrite a string with another smaller copy of itself - I can only move the substring into a newly defined variable that is predefined to fit the string (OK, vector).

Are either of these as expected?

Souphead.

**Comment by dtschump** [comment]
Everything seems quite logical to me right now.
Let me explain some aspects of the math parser to better understand how it works:

The most important point to know is that, once defined in the math evaluator, a variable cannot change its type. So you can't do this, for instance, 

    var = pi;          // Variable declaration + assignment.
    var = [0,1,2];     // Variable assignment with another type.

That's because the first assignment actually initializes both the variable type and its value, while the second assignment only updates the value of the variable. And if the types of the left-hand and right-hand operands are not compatible, the assignment throws an error. For a vector-valued variable (as a string), it is possible to update its value with an assignment only from a vector of the same size, or a scalar (in which case all vector components are set with the same value). In the math parser, vectors **have a fixed size**, which cannot be changed after the variable declaration. 
The same occurs for sub-vectors : the math compiler has to know the size of the vector you want to manipulate *at compilation time*, so you cannot ask for a subvector with non-constant indices.
Of course, if you write : 

    length = size(str) - 4;

then assigned _length_ will be always constant, but still, you can't write : 

    substr = str[0,length];

as _length_ is a variable that may have been assigned with another value before (it's actually hard for the compiler to know if a variable contains a pure constant value or not).
But, you can write : 

    substr = str[0,size(str)-4];

if you wish, because **size(str) - 4** is known to be a constant literal that cannot be modified (and thus is evaluated at compilation time).

Strings are vectors. So, you are right, a string cannot be overwritten with another string with a  different length (if the length of the second string is smaller, then you can **fake** it by inserting a *0* at the end of the smaller string, but still *size(str)* won't never change, so that's just a trick).
I don't think there are much limitations with this kind of behavior. If needed, it's always possible to work with big vectors (viewed as memory buffers), and insert some _0_ at the end of the strings if necessary. Most strings operations are possible. If you don't know how to do a particular operation, let me know, I'll be glad to help.

**Comment by souphead** [comment]
What I wanting to do is take an arbitrary sized string input and parse it. My first approach was to use variables to scan it (my first problem) and then to work from the front, chopping off what I had already used.

So what am I left with? May be the faking it by padding out the end with zeros might work. So if for simplicity, I start with a sting/vector of seven values and I want to remove the first three but I will need to add three zero/nulls at the end to balance the original seven. So, taking the 4 through 7 to the front would be: 
 
str = str[3,size(str)-4];

but I need to add the 3 zeros as well at the same time. What would that final syntax be? To be super clear, if str starts off as:
[ a, b, c, d, e, f, g ]
I need it to become:
[ d, e, f, g, 0, 0, 0 ]

Souphead.

**Comment by dtschump** [comment]
If you really want to manage complex operations with variable-length strings, then I'd say the math parser is maybe not the best tool to use. I've done a lot of string parsing operations in some G'MIC filters, and I found convenient to use the classical pipeline commands instead.
That being said, I'm sure we can use the math parser anyway for this kind of things.
In your simple case, I'd write : 

~~~~~~~~~~~
test :
  -echo {`"
str='hello friends';
str2=vector1024(0);
copy(str2[0],str[3],size(str)-3);
str2;
"`}
~~~~~~~~~~~
