### ISSUE TITLE
problem with colorize interactive and black lineart

### ISSUE THREAD

**Issue by narayaan** [dtschump/gmic-community#52]
I tried to use the colorize interactieve filter on lineart. I previously cleaned up this lineart and removed all whitespace, thus keeping only my black lineart.

The problem is, the colorize interactive filter is using a black background which makes the lineart undistinguishable form the background.

Is this something that can be solved?

**Comment by Anthony-Gaudino** [comment]
I tried this filter and it worked OK for me.

Try to update the plugin and check the documentation again.

If this doesn't help, I suggest you give more information about your problem, provide software version and screenshots, this will certainly help.

**Comment by narayaan** [comment]
This is an example of a problematic image, if I use the filter on images where I didn't remove the whitespace the problem doesn't occur

![image3344 2](https://cloud.githubusercontent.com/assets/12802235/16207680/bf9c732e-372e-11e6-881d-8021350240ca.png)

**Comment by narayaan** [comment]
Hi; i just retested it and the problem persists,
This image should illustrate the problem;
![path3346](https://cloud.githubusercontent.com/assets/12802235/16207802/67e956d2-372f-11e6-8223-751e79cca036.png)

**Comment by Anthony-Gaudino** [comment]
Here it also appears completely black when using the filter, but if you instead of a transparent background use a white one it works.

Here:
![painted_lineart](https://cloud.githubusercontent.com/assets/2439728/16212346/5700b87c-371d-11e6-8ea0-1760bd662672.png)

So, as it seems the filter requires that there's no transparency, just add a white layer on GIMP under your drawing layer and combine them to have a white background.

**Comment by narayaan** [comment]
Thanks a lot; this solves my issue!
