### ISSUE TITLE
Gmic 2.0.0 plugin preview problem

### ISSUE THREAD

**Issue by jludwin** [dtschump/gmic-community#79]
Hello,
First of all, thank you for the great tool.
I am using Gimp and G'MIC on Ubuntu 16.04 from the ppa:otto-kesselgulasch/gimp-edge repository.
I noticed that recently (most likely after update to version 2.0.0) preview for many filters got broken. The common part for every error message mentions -m* option which cannot be interpreted. Is there a way I can help in solving this problem?
Example message for Sharpen [deblur] filter:

`<gmic>-1./gui_error_preview/gui_print_preview/ Enter scope 'gui_print_preview/'.
<gmic>-1./gui_error_preview/gui_print_preview/ Item '-skip', selection [0].
<gmic>-1./gui_error_preview/gui_print_preview/ Command '-skip': arguments = 'Preview error:\,*** Error in ./fx_deblur_preview/gui_split_preview/*repeat/(...)/mix_rgb/mix_channels/*repeat/*local/ *** Unknown command or filename '-m*' (did you mean '-m' ?).'.
[gmic]-1./gui_error_preview/gui_print_preview/ Skip argument 'Preview error:,*** Error in ./fx_deblu(...)filename '-m*' (did you mean '-m' ?).'.
`

**Comment by dtschump** [comment]
Hello. You are probably using one of the early pre-version of G'MIC 2.0.0, which has evolved a lot since.
I encourage you to download the latest pre-version, available here : http://gmic.eu/files/prerelease/
and install it, instead of using the version from the PPA (or you can also ping the PPA maintainer to make him update this package).

**Comment by jludwin** [comment]
Thank you. The new version works great.
