### ISSUE TITLE
G'Mic seems not to load in GIMP 2.9.6

### ISSUE THREAD

**Issue by scalkosz** [dtschump/gmic-community#93]
Hi there,

I am using Win7 64bit. Installation of G'Mic as flawless, however it G'Mic is not displayed in GMP 2.9.6. Not even within the Plugin Browser.

When I run gmic_gimp_qt.exe I receive an error message saying: 'libidn-11.dll' is missig on this Computer. Please repeat installation. I have installed again but to no success?!

Please help

Kind regards

Stephan

**Comment by dtschump** [comment]
It seems other has this issue too, with latest development version of GIMP (2.9.6).

More info here : http://gimpchat.com/viewtopic.php?f=28&t=15844

I can't help much, as I don't use Windows myself. Sorry about that.

**Comment by scalkosz** [comment]
That looks very promising! Thanks a lot, I will give it a try

Kind regards

Stephan

**Comment by esrat** [comment]
Hi,
this cannot be the real issue!
I have the same problem on Win7 64bit and I get the same error when trying to start the 'gmic_gimp_qt.exe'. But I'm not using any development version of GIMP! Instead, I tried two different portable versions of GIMP (2.8.4 and 2.8.22 from portableapps.com) but never saw the filter menu entry for G'Mic or the registered plug-in itself. (I do see gmic mentioned on the starting splash screen and GIMP does also show the green icon on the added plug-in-folder.)
I also realized that the missing DLLs (more than one!) are already present within the gimp\bin directory. So this cannot be the problem, since this version of G'Mic is not intended to be run as a standalone application - and GIMP does already know these libraries. As a test I finally copied all the DLLs from this directory to the dedicated G'Mic-plug-in-directory. Following the 'gmic_gimp_qt.exe' did not miss anything anymore but still failed to start!
As another test I replaced the 'libcairo-2.dll' as mentioned in the linked chat, but than my GIMP portable 2.8.22 won't even start anymore!

**Comment by esrat** [comment]
Never mind my last comment.
My problems did arise; because I wasn't aware of the fact that portableapps.com does only provide 32bit builds of GIMP portable! So I was trying to install the 64bit version of G'Mic into the 32bit version of GIMP! ...
Now that I use the 32bit version, it works.
... I still let my comments here, in case that someone else runs into the same problems.
